apiVersion: v1
kind: Pod

metadata:
  name: myapp-pod
  namespace: default
  labels: 
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container-1
      image: nginx
     #command: []
      resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      

#to start 
#kubectl create -f pod-definition.yml      